# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scope/v1/common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'scope/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15scope/v1/common.proto\x12\x08scope.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"-\n\nPagination\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\"T\n\rPaginatedMeta\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x11\n\tpage_size\x18\x03 \x01(\x05\x12\x13\n\x0btotal_pages\x18\x04 \x01(\x05\"/\n\x08GeoPoint\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"%\n\x12HealthCheckRequest\x12\x0f\n\x07service\x18\x01 \x01(\t\"\xc0\x01\n\x13HealthCheckResponse\x12\x34\n\x06status\x18\x01 \x01(\x0e\x32$.scope.v1.HealthCheckResponse.Status\x12\x0f\n\x07version\x18\x02 \x01(\t\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"3\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x42\x36Z#scope-proto/gen/go/scope/v1;scopev1\xaa\x02\x0eScope.Proto.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scope.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#scope-proto/gen/go/scope/v1;scopev1\252\002\016Scope.Proto.V1'
  _globals['_PAGINATION']._serialized_start=68
  _globals['_PAGINATION']._serialized_end=113
  _globals['_PAGINATEDMETA']._serialized_start=115
  _globals['_PAGINATEDMETA']._serialized_end=199
  _globals['_GEOPOINT']._serialized_start=201
  _globals['_GEOPOINT']._serialized_end=248
  _globals['_HEALTHCHECKREQUEST']._serialized_start=250
  _globals['_HEALTHCHECKREQUEST']._serialized_end=287
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=290
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=482
  _globals['_HEALTHCHECKRESPONSE_STATUS']._serialized_start=431
  _globals['_HEALTHCHECKRESPONSE_STATUS']._serialized_end=482
# @@protoc_insertion_point(module_scope)
