# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scope/v1/common.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'scope/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15scope/v1/common.proto\x12\x08scope.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"=\n\nPagination\x12\x12\n\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n\tpage_size\x18\x02 \x01(\x05R\x08pageSize\"w\n\rPaginatedMeta\x12\x14\n\x05total\x18\x01 \x01(\x05R\x05total\x12\x12\n\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n\tpage_size\x18\x03 \x01(\x05R\x08pageSize\x12\x1f\n\x0btotal_pages\x18\x04 \x01(\x05R\ntotalPages\"D\n\x08GeoPoint\x12\x1a\n\x08latitude\x18\x01 \x01(\x01R\x08latitude\x12\x1c\n\tlongitude\x18\x02 \x01(\x01R\tlongitude\".\n\x12HealthCheckRequest\x12\x18\n\x07service\x18\x01 \x01(\tR\x07service\"\xdc\x01\n\x13HealthCheckResponse\x12<\n\x06status\x18\x01 \x01(\x0e\x32$.scope.v1.HealthCheckResponse.StatusR\x06status\x12\x18\n\x07version\x18\x02 \x01(\tR\x07version\x12\x38\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\ttimestamp\"3\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x42\x36Z#scope-proto/gen/go/scope/v1;scopev1\xaa\x02\x0eScope.Proto.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scope.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#scope-proto/gen/go/scope/v1;scopev1\252\002\016Scope.Proto.V1'
  _globals['_PAGINATION']._serialized_start=68
  _globals['_PAGINATION']._serialized_end=129
  _globals['_PAGINATEDMETA']._serialized_start=131
  _globals['_PAGINATEDMETA']._serialized_end=250
  _globals['_GEOPOINT']._serialized_start=252
  _globals['_GEOPOINT']._serialized_end=320
  _globals['_HEALTHCHECKREQUEST']._serialized_start=322
  _globals['_HEALTHCHECKREQUEST']._serialized_end=368
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=371
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=591
  _globals['_HEALTHCHECKRESPONSE_STATUS']._serialized_start=540
  _globals['_HEALTHCHECKRESPONSE_STATUS']._serialized_end=591
# @@protoc_insertion_point(module_scope)
