# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from scope.v1 import intel_pb2 as scope_dot_v1_dot_intel__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in scope/v1/intel_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IntelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeSentiment = channel.unary_unary(
                '/scope.v1.IntelService/AnalyzeSentiment',
                request_serializer=scope_dot_v1_dot_intel__pb2.SentimentRequest.SerializeToString,
                response_deserializer=scope_dot_v1_dot_intel__pb2.SentimentResponse.FromString,
                _registered_method=True)
        self.AnalyzeSentimentBatch = channel.unary_unary(
                '/scope.v1.IntelService/AnalyzeSentimentBatch',
                request_serializer=scope_dot_v1_dot_intel__pb2.SentimentBatchRequest.SerializeToString,
                response_deserializer=scope_dot_v1_dot_intel__pb2.SentimentBatchResponse.FromString,
                _registered_method=True)
        self.ClassifyImage = channel.unary_unary(
                '/scope.v1.IntelService/ClassifyImage',
                request_serializer=scope_dot_v1_dot_intel__pb2.ClassifyImageRequest.SerializeToString,
                response_deserializer=scope_dot_v1_dot_intel__pb2.ClassifyImageResponse.FromString,
                _registered_method=True)
        self.PredictTrip = channel.unary_unary(
                '/scope.v1.IntelService/PredictTrip',
                request_serializer=scope_dot_v1_dot_intel__pb2.PredictTripRequest.SerializeToString,
                response_deserializer=scope_dot_v1_dot_intel__pb2.PredictTripResponse.FromString,
                _registered_method=True)
        self.GetRecommendations = channel.unary_unary(
                '/scope.v1.IntelService/GetRecommendations',
                request_serializer=scope_dot_v1_dot_intel__pb2.RecommendationRequest.SerializeToString,
                response_deserializer=scope_dot_v1_dot_intel__pb2.RecommendationResponse.FromString,
                _registered_method=True)


class IntelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeSentiment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeSentimentBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictTrip(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeSentiment': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeSentiment,
                    request_deserializer=scope_dot_v1_dot_intel__pb2.SentimentRequest.FromString,
                    response_serializer=scope_dot_v1_dot_intel__pb2.SentimentResponse.SerializeToString,
            ),
            'AnalyzeSentimentBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeSentimentBatch,
                    request_deserializer=scope_dot_v1_dot_intel__pb2.SentimentBatchRequest.FromString,
                    response_serializer=scope_dot_v1_dot_intel__pb2.SentimentBatchResponse.SerializeToString,
            ),
            'ClassifyImage': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyImage,
                    request_deserializer=scope_dot_v1_dot_intel__pb2.ClassifyImageRequest.FromString,
                    response_serializer=scope_dot_v1_dot_intel__pb2.ClassifyImageResponse.SerializeToString,
            ),
            'PredictTrip': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictTrip,
                    request_deserializer=scope_dot_v1_dot_intel__pb2.PredictTripRequest.FromString,
                    response_serializer=scope_dot_v1_dot_intel__pb2.PredictTripResponse.SerializeToString,
            ),
            'GetRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendations,
                    request_deserializer=scope_dot_v1_dot_intel__pb2.RecommendationRequest.FromString,
                    response_serializer=scope_dot_v1_dot_intel__pb2.RecommendationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scope.v1.IntelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scope.v1.IntelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IntelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeSentiment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scope.v1.IntelService/AnalyzeSentiment',
            scope_dot_v1_dot_intel__pb2.SentimentRequest.SerializeToString,
            scope_dot_v1_dot_intel__pb2.SentimentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeSentimentBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scope.v1.IntelService/AnalyzeSentimentBatch',
            scope_dot_v1_dot_intel__pb2.SentimentBatchRequest.SerializeToString,
            scope_dot_v1_dot_intel__pb2.SentimentBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scope.v1.IntelService/ClassifyImage',
            scope_dot_v1_dot_intel__pb2.ClassifyImageRequest.SerializeToString,
            scope_dot_v1_dot_intel__pb2.ClassifyImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictTrip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scope.v1.IntelService/PredictTrip',
            scope_dot_v1_dot_intel__pb2.PredictTripRequest.SerializeToString,
            scope_dot_v1_dot_intel__pb2.PredictTripResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scope.v1.IntelService/GetRecommendations',
            scope_dot_v1_dot_intel__pb2.RecommendationRequest.SerializeToString,
            scope_dot_v1_dot_intel__pb2.RecommendationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
