# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scope/v1/spot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'scope/v1/spot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13scope/v1/spot.proto\x12\x08scope.v1\x1a\x15scope/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x99\x02\n\x04Spot\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12$\n\x08location\x18\x04 \x01(\x0b\x32\x12.scope.v1.GeoPoint\x12\x10\n\x08\x63\x61tegory\x18\x05 \x01(\t\x12\x0c\n\x04tags\x18\x06 \x03(\t\x12\x12\n\ncreator_id\x18\x07 \x01(\t\x12\x12\n\navg_rating\x18\x08 \x01(\x02\x12\x14\n\x0creview_count\x18\t \x01(\x05\x12.\n\ncreated_at\x18\n \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x0b \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x1c\n\x0eGetSpotRequest\x12\n\n\x02id\x18\x01 \x01(\t\"t\n\x10ListSpotsRequest\x12(\n\npagination\x18\x01 \x01(\x0b\x32\x14.scope.v1.Pagination\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x12\n\ncreator_id\x18\x03 \x01(\t\x12\x10\n\x08ordering\x18\x04 \x01(\t\"Y\n\x11ListSpotsResponse\x12\x1d\n\x05spots\x18\x01 \x03(\x0b\x32\x0e.scope.v1.Spot\x12%\n\x04meta\x18\x02 \x01(\x0b\x32\x17.scope.v1.PaginatedMeta\"f\n\x12SearchSpotsRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\"\n\x06\x63\x65nter\x18\x03 \x01(\x0b\x32\x12.scope.v1.GeoPoint\x12\x0e\n\x06radius\x18\x04 \x01(\t\"#\n\x14GetSpotsByIdsRequest\x12\x0b\n\x03ids\x18\x01 \x03(\t2\xa0\x02\n\x0bSpotService\x12\x33\n\x07GetSpot\x12\x18.scope.v1.GetSpotRequest\x1a\x0e.scope.v1.Spot\x12\x44\n\tListSpots\x12\x1a.scope.v1.ListSpotsRequest\x1a\x1b.scope.v1.ListSpotsResponse\x12H\n\x0bSearchSpots\x12\x1c.scope.v1.SearchSpotsRequest\x1a\x1b.scope.v1.ListSpotsResponse\x12L\n\rGetSpotsByIds\x12\x1e.scope.v1.GetSpotsByIdsRequest\x1a\x1b.scope.v1.ListSpotsResponseB6Z#scope-proto/gen/go/scope/v1;scopev1\xaa\x02\x0eScope.Proto.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scope.v1.spot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#scope-proto/gen/go/scope/v1;scopev1\252\002\016Scope.Proto.V1'
  _globals['_SPOT']._serialized_start=90
  _globals['_SPOT']._serialized_end=371
  _globals['_GETSPOTREQUEST']._serialized_start=373
  _globals['_GETSPOTREQUEST']._serialized_end=401
  _globals['_LISTSPOTSREQUEST']._serialized_start=403
  _globals['_LISTSPOTSREQUEST']._serialized_end=519
  _globals['_LISTSPOTSRESPONSE']._serialized_start=521
  _globals['_LISTSPOTSRESPONSE']._serialized_end=610
  _globals['_SEARCHSPOTSREQUEST']._serialized_start=612
  _globals['_SEARCHSPOTSREQUEST']._serialized_end=714
  _globals['_GETSPOTSBYIDSREQUEST']._serialized_start=716
  _globals['_GETSPOTSBYIDSREQUEST']._serialized_end=751
  _globals['_SPOTSERVICE']._serialized_start=754
  _globals['_SPOTSERVICE']._serialized_end=1042
# @@protoc_insertion_point(module_scope)
