apiVersion: v1
kind: Namespace
metadata:
  name: scope
  labels:
    app.kubernetes.io/name: scope
    app.kubernetes.io/part-of: scope-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: content-aws
  namespace: scope
  labels:
    app.kubernetes.io/name: content
    app.kubernetes.io/part-of: scope-platform
automountServiceAccountToken: false
