apiVersion: v1
kind: Secret
metadata:
  name: atlas-secrets
  namespace: atlas
  labels:
    app.kubernetes.io/name: atlas
    app.kubernetes.io/part-of: atlas-platform
type: Opaque
stringData:
  SA_PASSWORD: change-me-sql-password
  CORE_DB_CONNECTION: Server=sqlserver,1433;Database=AtlasDb;User Id=sa;Password=change-me-sql-password;TrustServerCertificate=True;
  ConnectionStrings__CoreDatabase: Server=sqlserver,1433;Database=AtlasDb;User Id=sa;Password=change-me-sql-password;TrustServerCertificate=True;
  CORE_JWT_SECRET: change-me-core-jwt-secret
  DJANGO_SECRET_KEY: change-me-django-secret
  FLASK_SECRET_KEY: change-me-flask-secret
  AWS_ACCESS_KEY_ID: change-me-aws-access-key-id
  AWS_SECRET_ACCESS_KEY: change-me-aws-secret-access-key
  VITE_MAPBOX_TOKEN: change-me-mapbox-token
