# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from scope.v1 import spot_pb2 as scope_dot_v1_dot_spot__pb2


class SpotServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSpot = channel.unary_unary(
                '/scope.v1.SpotService/GetSpot',
                request_serializer=scope_dot_v1_dot_spot__pb2.GetSpotRequest.SerializeToString,
                response_deserializer=scope_dot_v1_dot_spot__pb2.Spot.FromString,
                _registered_method=True)
        self.ListSpots = channel.unary_unary(
                '/scope.v1.SpotService/ListSpots',
                request_serializer=scope_dot_v1_dot_spot__pb2.ListSpotsRequest.SerializeToString,
                response_deserializer=scope_dot_v1_dot_spot__pb2.ListSpotsResponse.FromString,
                _registered_method=True)
        self.SearchSpots = channel.unary_unary(
                '/scope.v1.SpotService/SearchSpots',
                request_serializer=scope_dot_v1_dot_spot__pb2.SearchSpotsRequest.SerializeToString,
                response_deserializer=scope_dot_v1_dot_spot__pb2.ListSpotsResponse.FromString,
                _registered_method=True)
        self.GetSpotsByIds = channel.unary_unary(
                '/scope.v1.SpotService/GetSpotsByIds',
                request_serializer=scope_dot_v1_dot_spot__pb2.GetSpotsByIdsRequest.SerializeToString,
                response_deserializer=scope_dot_v1_dot_spot__pb2.ListSpotsResponse.FromString,
                _registered_method=True)


class SpotServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSpot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSpots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchSpots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSpotsByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSpot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSpot,
                    request_deserializer=scope_dot_v1_dot_spot__pb2.GetSpotRequest.FromString,
                    response_serializer=scope_dot_v1_dot_spot__pb2.Spot.SerializeToString,
            ),
            'ListSpots': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSpots,
                    request_deserializer=scope_dot_v1_dot_spot__pb2.ListSpotsRequest.FromString,
                    response_serializer=scope_dot_v1_dot_spot__pb2.ListSpotsResponse.SerializeToString,
            ),
            'SearchSpots': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchSpots,
                    request_deserializer=scope_dot_v1_dot_spot__pb2.SearchSpotsRequest.FromString,
                    response_serializer=scope_dot_v1_dot_spot__pb2.ListSpotsResponse.SerializeToString,
            ),
            'GetSpotsByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSpotsByIds,
                    request_deserializer=scope_dot_v1_dot_spot__pb2.GetSpotsByIdsRequest.FromString,
                    response_serializer=scope_dot_v1_dot_spot__pb2.ListSpotsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scope.v1.SpotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scope.v1.SpotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpotService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSpot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scope.v1.SpotService/GetSpot',
            scope_dot_v1_dot_spot__pb2.GetSpotRequest.SerializeToString,
            scope_dot_v1_dot_spot__pb2.Spot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSpots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scope.v1.SpotService/ListSpots',
            scope_dot_v1_dot_spot__pb2.ListSpotsRequest.SerializeToString,
            scope_dot_v1_dot_spot__pb2.ListSpotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchSpots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scope.v1.SpotService/SearchSpots',
            scope_dot_v1_dot_spot__pb2.SearchSpotsRequest.SerializeToString,
            scope_dot_v1_dot_spot__pb2.ListSpotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSpotsByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scope.v1.SpotService/GetSpotsByIds',
            scope_dot_v1_dot_spot__pb2.GetSpotsByIdsRequest.SerializeToString,
            scope_dot_v1_dot_spot__pb2.ListSpotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
