# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scope/v1/user.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'scope/v1/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from scope.v1 import common_pb2 as scope_dot_v1_dot_common__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13scope/v1/user.proto\x12\x08scope.v1\x1a\x15scope/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc5\x01\n\x04User\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n\x08username\x18\x02 \x01(\tR\x08username\x12\x14\n\x05\x65mail\x18\x03 \x01(\tR\x05\x65mail\x12!\n\x0c\x64isplay_name\x18\x04 \x01(\tR\x0b\x64isplayName\x12\x1d\n\navatar_url\x18\x05 \x01(\tR\tavatarUrl\x12\x39\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAt\" \n\x0eGetUserRequest\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"(\n\x14GetUsersByIdsRequest\x12\x10\n\x03ids\x18\x01 \x03(\tR\x03ids\"8\n\x10GetUsersResponse\x12$\n\x05users\x18\x01 \x03(\x0b\x32\x0e.scope.v1.UserR\x05users2\xdb\x01\n\x0bUserService\x12\x33\n\x07GetUser\x12\x18.scope.v1.GetUserRequest\x1a\x0e.scope.v1.User\x12K\n\rGetUsersByIds\x12\x1e.scope.v1.GetUsersByIdsRequest\x1a\x1a.scope.v1.GetUsersResponse\x12J\n\x0bHealthCheck\x12\x1c.scope.v1.HealthCheckRequest\x1a\x1d.scope.v1.HealthCheckResponseB6Z#scope-proto/gen/go/scope/v1;scopev1\xaa\x02\x0eScope.Proto.V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scope.v1.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#scope-proto/gen/go/scope/v1;scopev1\252\002\016Scope.Proto.V1'
  _globals['_USER']._serialized_start=90
  _globals['_USER']._serialized_end=287
  _globals['_GETUSERREQUEST']._serialized_start=289
  _globals['_GETUSERREQUEST']._serialized_end=321
  _globals['_GETUSERSBYIDSREQUEST']._serialized_start=323
  _globals['_GETUSERSBYIDSREQUEST']._serialized_end=363
  _globals['_GETUSERSRESPONSE']._serialized_start=365
  _globals['_GETUSERSRESPONSE']._serialized_end=421
  _globals['_USERSERVICE']._serialized_start=424
  _globals['_USERSERVICE']._serialized_end=643
# @@protoc_insertion_point(module_scope)
