# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from scope.v1 import common_pb2 as scope_dot_v1_dot_common__pb2
from scope.v1 import user_pb2 as scope_dot_v1_dot_user__pb2


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUser = channel.unary_unary(
                '/scope.v1.UserService/GetUser',
                request_serializer=scope_dot_v1_dot_user__pb2.GetUserRequest.SerializeToString,
                response_deserializer=scope_dot_v1_dot_user__pb2.User.FromString,
                _registered_method=True)
        self.GetUsersByIds = channel.unary_unary(
                '/scope.v1.UserService/GetUsersByIds',
                request_serializer=scope_dot_v1_dot_user__pb2.GetUsersByIdsRequest.SerializeToString,
                response_deserializer=scope_dot_v1_dot_user__pb2.GetUsersResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/scope.v1.UserService/HealthCheck',
                request_serializer=scope_dot_v1_dot_common__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=scope_dot_v1_dot_common__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsersByIds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=scope_dot_v1_dot_user__pb2.GetUserRequest.FromString,
                    response_serializer=scope_dot_v1_dot_user__pb2.User.SerializeToString,
            ),
            'GetUsersByIds': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsersByIds,
                    request_deserializer=scope_dot_v1_dot_user__pb2.GetUsersByIdsRequest.FromString,
                    response_serializer=scope_dot_v1_dot_user__pb2.GetUsersResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=scope_dot_v1_dot_common__pb2.HealthCheckRequest.FromString,
                    response_serializer=scope_dot_v1_dot_common__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scope.v1.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scope.v1.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scope.v1.UserService/GetUser',
            scope_dot_v1_dot_user__pb2.GetUserRequest.SerializeToString,
            scope_dot_v1_dot_user__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUsersByIds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scope.v1.UserService/GetUsersByIds',
            scope_dot_v1_dot_user__pb2.GetUsersByIdsRequest.SerializeToString,
            scope_dot_v1_dot_user__pb2.GetUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scope.v1.UserService/HealthCheck',
            scope_dot_v1_dot_common__pb2.HealthCheckRequest.SerializeToString,
            scope_dot_v1_dot_common__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
