# Generated by Django 5.1.7 on 2026-04-23 03:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creator_id', models.UUIDField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('planning', 'planning'), ('active', 'active'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='planning', max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('cover_photo_url', models.URLField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='spots.spot')),
            ],
            options={
                'unique_together': {('spot', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='TripMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('role', models.CharField(choices=[('owner', 'owner'), ('editor', 'editor'), ('viewer', 'viewer')], max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='trips.trip')),
            ],
            options={
                'unique_together': {('trip', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='TripSpot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_references', to='spots.spot')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_spots', to='trips.trip')),
            ],
            options={
                'ordering': ['day_number', 'sort_order', 'id'],
                'unique_together': {('trip', 'spot')},
            },
        ),
    ]
