# Generated by Django 5.1.7 on 2026-04-23 03:18

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('food', 'food'), ('nature', 'nature'), ('nightlife', 'nightlife'), ('culture', 'culture'), ('adventure', 'adventure'), ('shopping', 'shopping'), ('scenic', 'scenic'), ('other', 'other')], max_length=50)),
                ('vibe', models.CharField(blank=True, max_length=50)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('visited_at', models.DateField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='spots_spot_latitud_04a08f_idx'), models.Index(fields=['category'], name='spots_spot_categor_ef7cfb_idx')],
            },
        ),
    ]
