DECLARE @Now DATETIME2 = SYSUTCDATETIME();

DECLARE @Preferences TABLE (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    PreferredCategories NVARCHAR(500) NOT NULL,
    BudgetLevel NVARCHAR(20) NOT NULL,
    PacePreference NVARCHAR(20) NOT NULL,
    UpdatedOffsetHours INT NOT NULL
);

INSERT INTO @Preferences (Id, UserId, PreferredCategories, BudgetLevel, PacePreference, UpdatedOffsetHours)
VALUES
    ('eeeeeeee-eeee-eeee-eeee-000000000010', '99999999-9999-9999-9999-999999999991', N'culture,shopping,scenic', N'mid', N'balanced', 12),
    ('eeeeeeee-eeee-eeee-eeee-000000000011', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1', N'nature,adventure,scenic', N'low', N'relaxed', 13),
    ('eeeeeeee-eeee-eeee-eeee-000000000012', 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1', N'scenic,food,nightlife', N'high', N'active', 14),
    ('eeeeeeee-eeee-eeee-eeee-000000000013', 'cccccccc-cccc-cccc-cccc-ccccccccccc1', N'adventure,shopping,nature', N'mid', N'balanced', 15),
    ('eeeeeeee-eeee-eeee-eeee-000000000014', 'dddddddd-dddd-dddd-dddd-ddddddddddd1', N'culture,food,shopping', N'low', N'relaxed', 16),
    ('eeeeeeee-eeee-eeee-eeee-000000000015', 'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee9', N'scenic,shopping,culture', N'high', N'active', 17),
    ('eeeeeeee-eeee-eeee-eeee-000000000016', 'ffffffff-ffff-ffff-ffff-fffffffffff9', N'nightlife,food,culture', N'mid', N'balanced', 18),
    ('eeeeeeee-eeee-eeee-eeee-000000000017', 'abababab-abab-abab-abab-ababababab01', N'culture,scenic,food', N'low', N'relaxed', 19),
    ('eeeeeeee-eeee-eeee-eeee-000000000018', 'bcbcbcbc-bcbc-bcbc-bcbc-bcbcbcbcbc01', N'nature,scenic,food', N'high', N'active', 20),
    ('eeeeeeee-eeee-eeee-eeee-000000000019', 'cdcdcdcd-cdcd-cdcd-cdcd-cdcdcdcdcd01', N'culture,nature,scenic', N'mid', N'balanced', 21);

MERGE intel.UserPreferences AS target
USING @Preferences AS source
ON target.UserId = source.UserId
WHEN MATCHED THEN UPDATE SET
    PreferredCategories = source.PreferredCategories,
    BudgetLevel = source.BudgetLevel,
    PacePreference = source.PacePreference,
    UpdatedAt = DATEADD(HOUR, -source.UpdatedOffsetHours, @Now)
WHEN NOT MATCHED THEN INSERT (Id, UserId, PreferredCategories, BudgetLevel, PacePreference, UpdatedAt)
VALUES (source.Id, source.UserId, source.PreferredCategories, source.BudgetLevel, source.PacePreference, DATEADD(HOUR, -source.UpdatedOffsetHours, @Now));

DECLARE @SpotFeatures TABLE (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    SpotId UNIQUEIDENTIFIER NOT NULL,
    FeatureVector NVARCHAR(MAX) NOT NULL,
    PopularityScore FLOAT NOT NULL,
    SentimentScore FLOAT NOT NULL,
    UpdatedOffsetHours INT NOT NULL
);

INSERT INTO @SpotFeatures (Id, SpotId, FeatureVector, PopularityScore, SentimentScore, UpdatedOffsetHours)
VALUES
    ('f3000000-0000-0000-0000-000000000025', '90000000-0000-0000-0000-000000000025', N'{"category":"culture","vibe":"gallery crawl","pillars":["lively","photo-worthy","group-friendly"],"popularity":"steady","touristLocalMix":"locals, repeat Vegas visitors, and first-timers looking beyond the Strip","visitorIntent":"art walk, food trucks, murals, and pre-dinner wandering","crowdLevel":"busy on event nights","budgetBand":"low-mid","pace":"unhurried evening","seasonality":"best at sunset and early evening, fall through spring is most comfortable","groupFit":"friends, couples, solo culture travelers","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["culture","lively","photo-worthy","group-friendly","gallery crawl"]}', 0.72, 0.82, 3),
    ('f3000000-0000-0000-0000-000000000026', '90000000-0000-0000-0000-000000000026', N'{"category":"scenic","vibe":"surf town","pillars":["photo-worthy","worth-the-drive","lively"],"popularity":"high","touristLocalMix":"day-tripping visitors, surfers, families, and local lunch traffic","visitorIntent":"beach-town browsing, shave ice, surf watching, and coastal routing","crowdLevel":"busy midday and winter surf season","budgetBand":"mid","pace":"slow half-day","seasonality":"morning arrival keeps parking and heat manageable","groupFit":"families, couples, friend groups","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["scenic","photo-worthy","worth-the-drive","lively","surf town"]}', 0.74, 0.84, 4),
    ('f3000000-0000-0000-0000-000000000027', '90000000-0000-0000-0000-000000000027', N'{"category":"nightlife","vibe":"live music","pillars":["lively","group-friendly","date-night"],"popularity":"steady","touristLocalMix":"tourists, bachelor and friend groups, music fans, and service workers between shifts","visitorIntent":"live music, people-watching, late food, and high-energy nightlife","crowdLevel":"very busy at night and weekends","budgetBand":"mid-high","pace":"fast evening","seasonality":"best after dinner, shoulder season weekdays feel easier","groupFit":"groups and couples who want noise and music","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["nightlife","lively","group-friendly","date-night","live music"]}', 0.77, 0.86, 5),
    ('f3000000-0000-0000-0000-000000000028', '90000000-0000-0000-0000-000000000028', N'{"category":"scenic","vibe":"historic waterfront","pillars":["photo-worthy","calm","family-friendly"],"popularity":"steady","touristLocalMix":"heritage tourists, morning walkers, local runners, and family groups","visitorIntent":"waterfront photos, architecture, shade, and pre-brunch pacing","crowdLevel":"moderate, calmer early","budgetBand":"low","pace":"slow morning","seasonality":"best in spring/fall mornings or winter afternoons","groupFit":"families, couples, solo walkers","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["scenic","photo-worthy","calm","family-friendly","historic waterfront"]}', 0.79, 0.88, 6),
    ('f3000000-0000-0000-0000-000000000029', '90000000-0000-0000-0000-000000000029', N'{"category":"adventure","vibe":"red rock basecamp","pillars":["worth-the-drive","group-friendly","lively"],"popularity":"steady","touristLocalMix":"national park travelers, road trippers, guides, and outdoor crews","visitorIntent":"gear pickup, casual food, trail staging, and sunset-route planning","crowdLevel":"busy spring/fall, quieter winter","budgetBand":"mid","pace":"active half-day","seasonality":"spring and fall are strongest; early evening works after hikes","groupFit":"friends, solo hikers, couples","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["adventure","worth-the-drive","group-friendly","lively","red rock basecamp"]}', 0.82, 0.90, 7),
    ('f3000000-0000-0000-0000-000000000030', '90000000-0000-0000-0000-000000000030', N'{"category":"scenic","vibe":"red rock sunset","pillars":["photo-worthy","worth-the-drive","date-night"],"popularity":"high","touristLocalMix":"road trippers, couples, hikers, wellness travelers, and local sunset regulars","visitorIntent":"viewpoint timing, photography, light hiking, and dinner-before-or-after routing","crowdLevel":"crowded at sunset","budgetBand":"low-mid","pace":"slow golden hour","seasonality":"best near sunset outside peak summer heat","groupFit":"couples, solo photographers, small groups","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["scenic","photo-worthy","worth-the-drive","date-night","red rock sunset"]}', 0.84, 0.92, 8),
    ('f3000000-0000-0000-0000-000000000031', '90000000-0000-0000-0000-000000000031', N'{"category":"culture","vibe":"working studios","pillars":["hidden-gem","photo-worthy","lively"],"popularity":"steady","touristLocalMix":"regional weekenders, local artists, brewery-bound visitors, and design shoppers","visitorIntent":"studio browsing, murals, cafe stops, and low-pressure culture time","crowdLevel":"moderate, higher on weekends","budgetBand":"mid","pace":"unhurried afternoon","seasonality":"spring/fall afternoons are strongest","groupFit":"couples, friend groups, solo art travelers","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["culture","hidden-gem","photo-worthy","lively","working studios"]}', 0.87, 0.94, 9),
    ('f3000000-0000-0000-0000-000000000032', '90000000-0000-0000-0000-000000000032', N'{"category":"culture","vibe":"spa heritage","pillars":["family-friendly","photo-worthy","calm"],"popularity":"steady","touristLocalMix":"national park visitors, spa travelers, families, and local downtown walkers","visitorIntent":"heritage architecture, bathhouse history, easy park access, and low-impact wandering","crowdLevel":"moderate weekends","budgetBand":"low-mid","pace":"slow half-day","seasonality":"year-round, best morning or late afternoon","groupFit":"families, couples, solo history travelers","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["culture","family-friendly","photo-worthy","calm","spa heritage"]}', 0.90, 0.82, 10),
    ('f3000000-0000-0000-0000-000000000033', '90000000-0000-0000-0000-000000000033', N'{"category":"scenic","vibe":"roadside neon","pillars":["photo-worthy","quick-stop","budget-friendly"],"popularity":"steady","touristLocalMix":"road trippers, Route 66 fans, locals, and photo-stop travelers","visitorIntent":"neon photos, short walks, diner routing, and cross-state drive texture","crowdLevel":"light-moderate","budgetBand":"low","pace":"quick stop","seasonality":"best blue hour or evening","groupFit":"solo road trippers, couples, friends","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["scenic","photo-worthy","quick-stop","budget-friendly","roadside neon"]}', 0.92, 0.84, 11),
    ('f3000000-0000-0000-0000-000000000034', '90000000-0000-0000-0000-000000000034', N'{"category":"culture","vibe":"river monument","pillars":["family-friendly","photo-worthy","quick-stop"],"popularity":"steady","touristLocalMix":"families, school groups, first-time city visitors, and downtown walkers","visitorIntent":"monument photos, museum time, riverfront walks, and compact history","crowdLevel":"busy on holidays and summer weekends","budgetBand":"low-mid","pace":"balanced half-day","seasonality":"spring/fall daylight is easiest","groupFit":"families, groups, solo history travelers","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["culture","family-friendly","photo-worthy","quick-stop","river monument"]}', 0.72, 0.86, 12),
    ('f3000000-0000-0000-0000-000000000035', '90000000-0000-0000-0000-000000000035', N'{"category":"food","vibe":"market murals","pillars":["lively","budget-friendly","group-friendly"],"popularity":"steady","touristLocalMix":"locals, regional food shoppers, mural hunters, and weekend visitors","visitorIntent":"market food, murals, coffee, and neighborhood discovery","crowdLevel":"busy Saturday mornings","budgetBand":"low-mid","pace":"active morning","seasonality":"best Saturday morning, spring through fall feels strongest","groupFit":"friends, families, solo food travelers","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["food","lively","budget-friendly","group-friendly","market murals"]}', 0.74, 0.88, 13),
    ('f3000000-0000-0000-0000-000000000036', '90000000-0000-0000-0000-000000000036', N'{"category":"scenic","vibe":"garden classic","pillars":["family-friendly","calm","photo-worthy"],"popularity":"high","touristLocalMix":"locals on lunch walks, families, first-time Boston visitors, and students","visitorIntent":"garden strolls, photos, low-stress orientation, and nearby shopping/culture links","crowdLevel":"moderate in good weather","budgetBand":"low","pace":"slow short stop","seasonality":"spring blooms and fall color are strongest","groupFit":"families, couples, solo walkers","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["scenic","family-friendly","calm","photo-worthy","garden classic"]}', 0.77, 0.90, 14),
    ('f3000000-0000-0000-0000-000000000037', '90000000-0000-0000-0000-000000000037', N'{"category":"culture","vibe":"founding history","pillars":["family-friendly","quick-stop","photo-worthy"],"popularity":"steady","touristLocalMix":"families, school groups, history travelers, and Center City walkers","visitorIntent":"civic history, museum pairing, classic city photos, and compact routing","crowdLevel":"busy midday","budgetBand":"low-mid","pace":"balanced half-day","seasonality":"best morning, spring/fall or mild winter days","groupFit":"families, groups, solo history travelers","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["culture","family-friendly","quick-stop","photo-worthy","founding history"]}', 0.79, 0.92, 15),
    ('f3000000-0000-0000-0000-000000000038', '90000000-0000-0000-0000-000000000038', N'{"category":"nature","vibe":"rocky coast","pillars":["photo-worthy","worth-the-drive","calm"],"popularity":"high","touristLocalMix":"national park travelers, photographers, hikers, and coastal road trippers","visitorIntent":"sunrise views, easy hiking, rocky shoreline, and park-day sequencing","crowdLevel":"busy in summer, calmer at dawn","budgetBand":"low","pace":"early slow walk","seasonality":"late spring through fall, sunrise is strongest","groupFit":"solo hikers, couples, families with sturdy shoes","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["nature","photo-worthy","worth-the-drive","calm","rocky coast"]}', 0.82, 0.94, 16),
    ('f3000000-0000-0000-0000-000000000039', '90000000-0000-0000-0000-000000000039', N'{"category":"nature","vibe":"alpine lake","pillars":["photo-worthy","worth-the-drive","family-friendly"],"popularity":"high","touristLocalMix":"national park visitors, hikers, families, and road-trip photographers","visitorIntent":"lake views, boat access, trailheads, and early-day park planning","crowdLevel":"busy in summer","budgetBand":"low-mid","pace":"active morning","seasonality":"June to September mornings are strongest","groupFit":"families, hikers, couples","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["nature","photo-worthy","worth-the-drive","family-friendly","alpine lake"]}', 0.84, 0.82, 17),
    ('f3000000-0000-0000-0000-000000000040', '90000000-0000-0000-0000-000000000040', N'{"category":"scenic","vibe":"mountain road","pillars":["worth-the-drive","photo-worthy","quick-stop"],"popularity":"high","touristLocalMix":"park road trippers, photographers, hikers, and families with timed-entry plans","visitorIntent":"viewpoint stops, scenic driving, short walks, and route pacing","crowdLevel":"crowded in peak summer","budgetBand":"low","pace":"slow drive","seasonality":"summer opening window, morning light is best","groupFit":"couples, families, road-trip groups","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["scenic","worth-the-drive","photo-worthy","quick-stop","mountain road"]}', 0.87, 0.84, 18),
    ('f3000000-0000-0000-0000-000000000041', '90000000-0000-0000-0000-000000000041', N'{"category":"shopping","vibe":"bookstore district","pillars":["calm","budget-friendly","solo-friendly"],"popularity":"steady","touristLocalMix":"locals, solo travelers, book shoppers, coffee seekers, and rainy-day visitors","visitorIntent":"book browsing, cafes, galleries, and weather-proof city time","crowdLevel":"moderate weekends","budgetBand":"low-mid","pace":"slow afternoon","seasonality":"year-round, especially useful on rainy afternoons","groupFit":"solo travelers, couples, small groups","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["shopping","calm","budget-friendly","solo-friendly","bookstore district"]}', 0.90, 0.86, 19),
    ('f3000000-0000-0000-0000-000000000042', '90000000-0000-0000-0000-000000000042', N'{"category":"culture","vibe":"adobe galleries","pillars":["photo-worthy","calm"],"popularity":"steady","touristLocalMix":"art travelers, locals, couples, and regional weekend visitors","visitorIntent":"gallery browsing, plaza walks, jewelry shopping, and heritage architecture","crowdLevel":"moderate, heavier during festivals","budgetBand":"mid-high","pace":"slow afternoon","seasonality":"spring/fall afternoons are easiest","groupFit":"couples, solo art travelers, friends","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["culture","photo-worthy","calm","adobe galleries"]}', 0.92, 0.88, 20),
    ('f3000000-0000-0000-0000-000000000043', '90000000-0000-0000-0000-000000000043', N'{"category":"scenic","vibe":"shaded squares","pillars":["photo-worthy","calm","family-friendly"],"popularity":"high","touristLocalMix":"weekend visitors, locals, families, wedding parties, and architecture walkers","visitorIntent":"park photos, shaded walking, cafe routing, and historic district orientation","crowdLevel":"moderate, busier in spring","budgetBand":"low","pace":"slow morning","seasonality":"spring and fall mornings are strongest","groupFit":"families, couples, solo walkers","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["scenic","photo-worthy","calm","family-friendly","shaded squares"]}', 0.72, 0.90, 21),
    ('f3000000-0000-0000-0000-000000000044', '90000000-0000-0000-0000-000000000044', N'{"category":"nature","vibe":"coastal trail","pillars":["solo-friendly","photo-worthy","worth-the-drive"],"popularity":"high","touristLocalMix":"locals, cruise-extension visitors, cyclists, runners, and wildlife-curious travelers","visitorIntent":"bike rides, skyline and inlet views, easy nature access, and layover-friendly pacing","crowdLevel":"moderate in summer","budgetBand":"low-mid","pace":"active half-day","seasonality":"summer evenings and clear mornings are strongest","groupFit":"solo travelers, couples, active families","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["nature","solo-friendly","photo-worthy","worth-the-drive","coastal trail"]}', 0.74, 0.92, 22),
    ('f3000000-0000-0000-0000-000000000045', '90000000-0000-0000-0000-000000000045', N'{"category":"scenic","vibe":"gulf ferry","pillars":["family-friendly","worth-the-drive","calm"],"popularity":"steady","touristLocalMix":"families, beach travelers, casino-weekend visitors, and park day trippers","visitorIntent":"ferry staging, gulf views, beach access, and relaxed coastal timing","crowdLevel":"seasonal and weather-dependent","budgetBand":"mid","pace":"slow half-day","seasonality":"spring/fall and calm summer mornings work best","groupFit":"families, couples, small groups","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["scenic","family-friendly","worth-the-drive","calm","gulf ferry"]}', 0.77, 0.94, 23),
    ('f3000000-0000-0000-0000-000000000046', '90000000-0000-0000-0000-000000000046', N'{"category":"scenic","vibe":"city greenway","pillars":["family-friendly","quick-stop","calm"],"popularity":"steady","touristLocalMix":"locals, families, downtown workers, and weekend visitors pairing food and museums","visitorIntent":"greenway walks, skyline views, picnic breaks, and easy civic routing","crowdLevel":"moderate during events","budgetBand":"low","pace":"short reset","seasonality":"spring/fall evenings are strongest","groupFit":"families, solo walkers, couples","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["scenic","family-friendly","quick-stop","calm","city greenway"]}', 0.79, 0.82, 24),
    ('f3000000-0000-0000-0000-000000000047', '90000000-0000-0000-0000-000000000047', N'{"category":"food","vibe":"warehouse dining","pillars":["lively","group-friendly","date-night"],"popularity":"steady","touristLocalMix":"locals, bourbon travelers, food-focused visitors, and convention groups","visitorIntent":"restaurants, boutiques, murals, and evening route building","crowdLevel":"busy weekend nights","budgetBand":"mid-high","pace":"active evening","seasonality":"best dinner window, spring/fall patios help","groupFit":"groups, couples, food travelers","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["food","lively","group-friendly","date-night","warehouse dining"]}', 0.82, 0.84, 25),
    ('f3000000-0000-0000-0000-000000000048', '90000000-0000-0000-0000-000000000048', N'{"category":"food","vibe":"heritage lunch","pillars":["hidden-gem","budget-friendly","quick-stop"],"popularity":"steady","touristLocalMix":"locals, regional visitors, road trippers, and food-curious downtown walkers","visitorIntent":"lunch, cultural context, compact walking, and a low-pressure city stop","crowdLevel":"light-moderate","budgetBand":"low-mid","pace":"short midday","seasonality":"year-round lunch window","groupFit":"solo travelers, couples, small groups","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["food","hidden-gem","budget-friendly","quick-stop","heritage lunch"]}', 0.84, 0.86, 26),
    ('f3000000-0000-0000-0000-000000000049', '90000000-0000-0000-0000-000000000049', N'{"category":"scenic","vibe":"coastal mansions","pillars":["photo-worthy","date-night","calm"],"popularity":"high","touristLocalMix":"regional weekenders, mansion-tour visitors, couples, and coastal walkers","visitorIntent":"ocean views, architecture, light exercise, and dinner-before-or-after routing","crowdLevel":"busy summer weekends","budgetBand":"low-mid","pace":"slow walk","seasonality":"spring/fall afternoons are strongest","groupFit":"couples, families with older kids, solo walkers","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["scenic","photo-worthy","date-night","calm","coastal mansions"]}', 0.87, 0.88, 27),
    ('f3000000-0000-0000-0000-000000000050', '90000000-0000-0000-0000-000000000050', N'{"category":"nature","vibe":"lakefront bikes","pillars":["family-friendly","calm","photo-worthy"],"popularity":"steady","touristLocalMix":"locals, college visitors, leaf-peepers, cyclists, and families","visitorIntent":"lake views, biking, picnic breaks, and relaxed downtown pairing","crowdLevel":"moderate in summer/fall","budgetBand":"low","pace":"slow half-day","seasonality":"summer evenings and fall afternoons are strongest","groupFit":"families, couples, solo cyclists","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["nature","family-friendly","calm","photo-worthy","lakefront bikes"]}', 0.90, 0.90, 28),
    ('f3000000-0000-0000-0000-000000000051', '90000000-0000-0000-0000-000000000051', N'{"category":"scenic","vibe":"river mills","pillars":["photo-worthy","solo-friendly","quick-stop"],"popularity":"high","touristLocalMix":"locals, museum visitors, runners, photographers, and first-time city walkers","visitorIntent":"river views, skyline, mill history, and easy culture pairing","crowdLevel":"moderate, busy at sunset","budgetBand":"low","pace":"short walk","seasonality":"spring through fall, golden hour works well","groupFit":"solo travelers, couples, families","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["scenic","photo-worthy","solo-friendly","quick-stop","river mills"]}', 0.92, 0.92, 29),
    ('f3000000-0000-0000-0000-000000000052', '90000000-0000-0000-0000-000000000052', N'{"category":"food","vibe":"market hall","pillars":["group-friendly","budget-friendly","lively"],"popularity":"steady","touristLocalMix":"locals, lakefront visitors, convention groups, and food-focused weekenders","visitorIntent":"food hall browsing, riverwalk pairing, and flexible group meals","crowdLevel":"busy weekend lunch","budgetBand":"low-mid","pace":"balanced lunch","seasonality":"year-round, especially useful in cold weather","groupFit":"groups, families, solo food travelers","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["food","group-friendly","budget-friendly","lively","market hall"]}', 0.72, 0.94, 30),
    ('f3000000-0000-0000-0000-000000000053', '90000000-0000-0000-0000-000000000053', N'{"category":"culture","vibe":"river museum","pillars":["photo-worthy","date-night","quick-stop"],"popularity":"high","touristLocalMix":"first-time visitors, museum travelers, locals crossing the river, and couples","visitorIntent":"museum exterior, river walk, golden-hour photos, and dinner routing","crowdLevel":"busy most seasons","budgetBand":"low-mid","pace":"slow evening","seasonality":"spring/fall evenings and winter blue hour work well","groupFit":"couples, solo culture travelers, families","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["culture","photo-worthy","date-night","quick-stop","river museum"]}', 0.74, 0.82, 31),
    ('f3000000-0000-0000-0000-000000000054', '90000000-0000-0000-0000-000000000054', N'{"category":"culture","vibe":"park gallery","pillars":["calm","photo-worthy","family-friendly"],"popularity":"high","touristLocalMix":"locals, art travelers, families, and city-break visitors","visitorIntent":"park walking, glasshouse photos, museum pairing, and relaxed afternoon pacing","crowdLevel":"moderate weekends","budgetBand":"low","pace":"slow afternoon","seasonality":"spring/fall afternoons are strongest","groupFit":"families, couples, solo walkers","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["culture","calm","photo-worthy","family-friendly","park gallery"]}', 0.77, 0.84, 32),
    ('f3000000-0000-0000-0000-000000000055', '90000000-0000-0000-0000-000000000055', N'{"category":"culture","vibe":"ancient icon","pillars":["photo-worthy","family-friendly","worth-the-drive"],"popularity":"high","touristLocalMix":"first-time tourists, school groups, history travelers, and locals moving through the center","visitorIntent":"ancient-site orientation, photos, guided tours, and compact walking","crowdLevel":"very busy midday","budgetBand":"mid","pace":"balanced half-day","seasonality":"early morning or late afternoon outside peak summer heat","groupFit":"families, couples, solo history travelers","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["culture","photo-worthy","family-friendly","worth-the-drive","ancient icon"]}', 0.79, 0.86, 33),
    ('f3000000-0000-0000-0000-000000000056', '90000000-0000-0000-0000-000000000056', N'{"category":"culture","vibe":"fashion piazza","pillars":["photo-worthy","luxury-feel"],"popularity":"high","touristLocalMix":"fashion shoppers, architecture fans, business travelers, and first-time Italy visitors","visitorIntent":"cathedral views, roof tickets, gallery shopping, and aperitivo routing","crowdLevel":"busy all day","budgetBand":"mid-high","pace":"balanced afternoon","seasonality":"morning for photos, evening for atmosphere","groupFit":"couples, solo city travelers, groups","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["culture","photo-worthy","luxury-feel","fashion piazza"]}', 0.82, 0.88, 34),
    ('f3000000-0000-0000-0000-000000000057', '90000000-0000-0000-0000-000000000057', N'{"category":"culture","vibe":"temple palace","pillars":["photo-worthy","family-friendly","worth-the-drive"],"popularity":"high","touristLocalMix":"international tourists, regional visitors, guides, and temple-focused travelers","visitorIntent":"palace visit, river routing, cultural orientation, and heat-aware morning planning","crowdLevel":"very busy and hot midday","budgetBand":"mid","pace":"structured morning","seasonality":"early morning, dry season is easiest","groupFit":"families, groups, solo culture travelers","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["culture","photo-worthy","family-friendly","worth-the-drive","temple palace"]}', 0.84, 0.90, 35),
    ('f3000000-0000-0000-0000-000000000058', '90000000-0000-0000-0000-000000000058', N'{"category":"scenic","vibe":"harbor skyline","pillars":["photo-worthy","date-night","worth-the-drive"],"popularity":"high","touristLocalMix":"first-time visitors, families, skyline photographers, and evening-date crowds","visitorIntent":"tram ride, harbor views, night photos, and compact landmark routing","crowdLevel":"busy at sunset","budgetBand":"mid","pace":"structured evening","seasonality":"clear evenings, weekdays reduce queues","groupFit":"couples, families, solo photographers","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["scenic","photo-worthy","date-night","worth-the-drive","harbor skyline"]}', 0.87, 0.92, 36),
    ('f3000000-0000-0000-0000-000000000059', '90000000-0000-0000-0000-000000000059', N'{"category":"scenic","vibe":"river tiles","pillars":["photo-worthy","date-night","lively"],"popularity":"high","touristLocalMix":"city-break travelers, locals near the river, wine tourists, and couples","visitorIntent":"riverside walk, tile facades, bridge views, and dinner routing","crowdLevel":"busy sunset and weekends","budgetBand":"mid","pace":"slow evening","seasonality":"spring/fall evenings are strongest","groupFit":"couples, friends, solo photographers","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["scenic","photo-worthy","date-night","lively","river tiles"]}', 0.90, 0.94, 37),
    ('f3000000-0000-0000-0000-000000000060', '90000000-0000-0000-0000-000000000060', N'{"category":"culture","vibe":"island shrine","pillars":["photo-worthy","worth-the-drive","family-friendly"],"popularity":"high","touristLocalMix":"Japan rail travelers, families, shrine visitors, and photographers","visitorIntent":"ferry day trip, shrine timing, tide-aware photos, and gentle island walking","crowdLevel":"busy during holidays","budgetBand":"mid","pace":"slow day trip","seasonality":"spring/fall and tide-aware windows are strongest","groupFit":"families, couples, solo travelers","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["culture","photo-worthy","worth-the-drive","family-friendly","island shrine"]}', 0.92, 0.82, 38),
    ('f3000000-0000-0000-0000-000000000061', '90000000-0000-0000-0000-000000000061', N'{"category":"scenic","vibe":"canal evening","pillars":["photo-worthy","date-night","calm"],"popularity":"high","touristLocalMix":"city-break visitors, locals biking home, couples, and museum travelers","visitorIntent":"canal photos, bridge walks, cafe timing, and low-stress orientation","crowdLevel":"moderate, busy in peak summer","budgetBand":"low-mid","pace":"slow evening","seasonality":"golden hour, spring/fall shoulder seasons","groupFit":"couples, solo walkers, small groups","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["scenic","photo-worthy","date-night","calm","canal evening"]}', 0.72, 0.84, 39),
    ('f3000000-0000-0000-0000-000000000062', '90000000-0000-0000-0000-000000000062', N'{"category":"culture","vibe":"hillside harbor","pillars":["photo-worthy","lively","worth-the-drive"],"popularity":"high","touristLocalMix":"locals, international visitors, food walkers, and photographers","visitorIntent":"tower views, steep streets, ferry links, and layered neighborhood browsing","crowdLevel":"busy midday and sunset","budgetBand":"low-mid","pace":"active afternoon","seasonality":"spring/fall afternoons are strongest","groupFit":"couples, friends, solo walkers comfortable with hills","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["culture","photo-worthy","lively","worth-the-drive","hillside harbor"]}', 0.74, 0.86, 40),
    ('f3000000-0000-0000-0000-000000000063', '90000000-0000-0000-0000-000000000063', N'{"category":"scenic","vibe":"creek lights","pillars":["family-friendly","date-night","photo-worthy"],"popularity":"steady","touristLocalMix":"families, stopover travelers, residents, and first-time visitors balancing old/new Dubai","visitorIntent":"creekside walking, dinner, heritage-style streets, and night photos","crowdLevel":"moderate-busy in cool months","budgetBand":"mid","pace":"slow evening","seasonality":"best at night, October through April","groupFit":"families, couples, groups","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["scenic","family-friendly","date-night","photo-worthy","creek lights"]}', 0.77, 0.88, 41),
    ('f3000000-0000-0000-0000-000000000064', '90000000-0000-0000-0000-000000000064', N'{"category":"culture","vibe":"hanok lanes","pillars":["photo-worthy","calm","quick-stop"],"popularity":"steady","touristLocalMix":"culture travelers, photographers, locals passing through, and first-time Seoul visitors","visitorIntent":"traditional lanes, viewpoint walking, cafe pairing, and respectful quiet routing","crowdLevel":"busy midday, residential quiet needed","budgetBand":"low","pace":"slow morning","seasonality":"morning or weekday shoulder times are best","groupFit":"solo travelers, couples, small respectful groups","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["culture","photo-worthy","calm","quick-stop","hanok lanes"]}', 0.79, 0.90, 42),
    ('f3000000-0000-0000-0000-000000000065', '90000000-0000-0000-0000-000000000065', N'{"category":"culture","vibe":"torii trail","pillars":["photo-worthy","worth-the-drive","solo-friendly"],"popularity":"high","touristLocalMix":"Japan travelers, shrine visitors, hikers, photographers, and families","visitorIntent":"shrine walk, torii photos, early timing, and optional hike extension","crowdLevel":"very busy after breakfast","budgetBand":"low","pace":"active morning","seasonality":"dawn or early morning year-round","groupFit":"solo travelers, couples, families ready for stairs","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["culture","photo-worthy","worth-the-drive","solo-friendly","torii trail"]}', 0.82, 0.92, 43),
    ('f3000000-0000-0000-0000-000000000066', '90000000-0000-0000-0000-000000000066', N'{"category":"food","vibe":"market tango","pillars":["lively","budget-friendly","photo-worthy"],"popularity":"steady","touristLocalMix":"locals, antiques browsers, food travelers, tango-curious visitors, and weekend groups","visitorIntent":"market food, street music, antiques, and neighborhood walking","crowdLevel":"busy Sundays","budgetBand":"low-mid","pace":"active Sunday","seasonality":"Sunday late morning into afternoon","groupFit":"friends, solo food travelers, couples","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["food","lively","budget-friendly","photo-worthy","market tango"]}', 0.84, 0.94, 44),
    ('f3000000-0000-0000-0000-000000000067', '90000000-0000-0000-0000-000000000067', N'{"category":"scenic","vibe":"bay cable car","pillars":["photo-worthy","worth-the-drive","date-night"],"popularity":"high","touristLocalMix":"first-time Rio visitors, families, photographers, and sunset planners","visitorIntent":"cable car ride, bay views, sunset photos, and skyline orientation","crowdLevel":"busy at sunset","budgetBand":"mid-high","pace":"structured half-day","seasonality":"clear mornings or sunset, weather visibility matters","groupFit":"families, couples, solo photographers","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["scenic","photo-worthy","worth-the-drive","date-night","bay cable car"]}', 0.87, 0.82, 45),
    ('f3000000-0000-0000-0000-000000000068', '90000000-0000-0000-0000-000000000068', N'{"category":"food","vibe":"night market","pillars":["lively","photo-worthy","group-friendly"],"popularity":"steady","touristLocalMix":"international tourists, local vendors, families, and guided food walkers","visitorIntent":"night-market energy, food stalls, orientation, and cautious group wandering","crowdLevel":"very busy at night","budgetBand":"low-mid","pace":"fast evening","seasonality":"evening outside peak summer heat","groupFit":"groups, couples comfortable with crowds, guided solo travelers","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["food","lively","photo-worthy","group-friendly","night market"]}', 0.90, 0.84, 46),
    ('f3000000-0000-0000-0000-000000000069', '90000000-0000-0000-0000-000000000069', N'{"category":"culture","vibe":"desert monuments","pillars":["photo-worthy","worth-the-drive","family-friendly"],"popularity":"high","touristLocalMix":"international tourists, history travelers, families, guides, and photographers","visitorIntent":"monument visit, early photos, heat management, and guided routing","crowdLevel":"busy and hot midday","budgetBand":"mid","pace":"structured morning","seasonality":"first light or early morning, cooler months easiest","groupFit":"families, groups, solo history travelers with guides","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["culture","photo-worthy","worth-the-drive","family-friendly","desert monuments"]}', 0.92, 0.86, 47),
    ('f3000000-0000-0000-0000-000000000070', '90000000-0000-0000-0000-000000000070', N'{"category":"scenic","vibe":"tower park","pillars":["photo-worthy","family-friendly","quick-stop"],"popularity":"high","touristLocalMix":"families, business travelers, stopover visitors, and evening walkers","visitorIntent":"tower photos, park break, mall/dinner pairing, and easy transit access","crowdLevel":"busy at night","budgetBand":"low-mid","pace":"short evening","seasonality":"evening fountain windows and clear nights","groupFit":"families, couples, solo stopover travelers","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["scenic","photo-worthy","family-friendly","quick-stop","tower park"]}', 0.72, 0.88, 48),
    ('f3000000-0000-0000-0000-000000000071', '90000000-0000-0000-0000-000000000071', N'{"category":"culture","vibe":"heritage square","pillars":["photo-worthy","quick-stop","family-friendly"],"popularity":"steady","touristLocalMix":"day trippers, families, heritage walkers, and food snackers","visitorIntent":"Portuguese-style streets, snacks, photos, and compact day-trip routing","crowdLevel":"busy midday","budgetBand":"low-mid","pace":"balanced afternoon","seasonality":"weekday mornings or late afternoon are easiest","groupFit":"families, couples, small groups","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["culture","photo-worthy","quick-stop","family-friendly","heritage square"]}', 0.74, 0.90, 49),
    ('f3000000-0000-0000-0000-000000000072', '90000000-0000-0000-0000-000000000072', N'{"category":"nature","vibe":"ricefield ridge","pillars":["calm","photo-worthy","solo-friendly"],"popularity":"high","touristLocalMix":"wellness travelers, local walkers, photographers, and slow-travel visitors","visitorIntent":"dawn walk, greenery, cafe finish, and low-cost outdoor reset","crowdLevel":"moderate after sunrise","budgetBand":"low","pace":"slow morning","seasonality":"dawn, dry-season mornings are easiest","groupFit":"solo travelers, couples, small groups","accessibilityFamilyFit":"standard city/outdoor access varies by exact route","signatureInterests":["nature","calm","photo-worthy","solo-friendly","ricefield ridge"]}', 0.77, 0.92, 50);

MERGE intel.SpotFeatures AS target
USING @SpotFeatures AS source
ON target.SpotId = source.SpotId
WHEN MATCHED THEN UPDATE SET
    FeatureVector = source.FeatureVector,
    PopularityScore = source.PopularityScore,
    SentimentScore = source.SentimentScore,
    UpdatedAt = DATEADD(HOUR, -source.UpdatedOffsetHours, @Now)
WHEN NOT MATCHED THEN INSERT (Id, SpotId, FeatureVector, PopularityScore, SentimentScore, UpdatedAt)
VALUES (source.Id, source.SpotId, source.FeatureVector, source.PopularityScore, source.SentimentScore, DATEADD(HOUR, -source.UpdatedOffsetHours, @Now));

MERGE intel.ItineraryCache AS target
USING (
    SELECT CAST('13131313-1313-1313-1313-000000000005' AS UNIQUEIDENTIFIER) AS Id, CAST('eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee9' AS UNIQUEIDENTIFIER) AS UserId, N'demo-trip-5-showcase-route' AS RequestHash, N'{"title":"Desert Lights to Canyon Country","destination":"Las Vegas, Moab, Sedona","stops":["Las Vegas Arts District First Friday","Moab Main Street Canyon Base","Sedona Airport Mesa Sunset"],"estimatedBudget":1620,"grounding":"verified seeded public places"}' AS ResultJson, DATEADD(DAY, 14, @Now) AS ExpiresAt, DATEADD(HOUR, -2, @Now) AS CreatedAt
    UNION ALL
    SELECT CAST('13131313-1313-1313-1313-000000000006' AS UNIQUEIDENTIFIER) AS Id, CAST('ffffffff-ffff-ffff-ffff-fffffffffff9' AS UNIQUEIDENTIFIER) AS UserId, N'demo-trip-6-showcase-route' AS RequestHash, N'{"title":"Southern Music and Coastal Cities","destination":"Nashville, Charleston, Savannah, Biloxi, Birmingham","stops":["Nashville Broadway Live Block","Charleston Battery Morning Walk","Savannah Forsyth Fountain Loop","Biloxi Gulf Islands Ferry Dock","Birmingham Railroad Park Greenway"],"estimatedBudget":1880,"grounding":"verified seeded public places"}' AS ResultJson, DATEADD(DAY, 14, @Now) AS ExpiresAt, DATEADD(HOUR, -3, @Now) AS CreatedAt
    UNION ALL
    SELECT CAST('13131313-1313-1313-1313-000000000007' AS UNIQUEIDENTIFIER) AS Id, CAST('cccccccc-cccc-cccc-cccc-ccccccccccc1' AS UNIQUEIDENTIFIER) AS UserId, N'demo-trip-7-showcase-route' AS RequestHash, N'{"title":"Route 66 Heartland Weekend","destination":"Tulsa, St. Louis, Chicago","stops":["Tulsa Route 66 Neon Gateway","St. Louis Gateway Arch Riverfront","Millennium Park Bean Loop"],"estimatedBudget":980,"grounding":"verified seeded public places"}' AS ResultJson, DATEADD(DAY, 14, @Now) AS ExpiresAt, DATEADD(HOUR, -4, @Now) AS CreatedAt
    UNION ALL
    SELECT CAST('13131313-1313-1313-1313-000000000008' AS UNIQUEIDENTIFIER) AS Id, CAST('cdcdcdcd-cdcd-cdcd-cdcd-cdcdcdcdcd01' AS UNIQUEIDENTIFIER) AS UserId, N'demo-trip-8-showcase-route' AS RequestHash, N'{"title":"Northern Lakes and Market Cities","destination":"Minneapolis, Milwaukee, Detroit, Chicago","stops":["Minneapolis Stone Arch River View","Milwaukee Third Ward Market","Detroit Eastern Market Saturday","Millennium Park Bean Loop"],"estimatedBudget":1320,"grounding":"verified seeded public places"}' AS ResultJson, DATEADD(DAY, 14, @Now) AS ExpiresAt, DATEADD(HOUR, -5, @Now) AS CreatedAt
) AS source
ON target.RequestHash = source.RequestHash
WHEN MATCHED THEN UPDATE SET
    UserId = source.UserId,
    ResultJson = source.ResultJson,
    ExpiresAt = source.ExpiresAt
WHEN NOT MATCHED THEN INSERT (Id, UserId, RequestHash, ResultJson, ExpiresAt, CreatedAt)
VALUES (source.Id, source.UserId, source.RequestHash, source.ResultJson, source.ExpiresAt, source.CreatedAt);
GO
